name: Controlling execution flow
description: Controlling execution flows

on:
    push:
    workflow_dispatch:

jobs:

  dev-bulid:
    runs-on: ubuntu-latest
    steps:
      - name: bulid dev
        run: echo 'building dev'
  dev-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: unit test dev
        run: echo 'unit test in dev'
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy in dev
        run: echo 'Im in dev'
  
  uat:
    runs-on: ubuntu-latest
    needs: dev-deploy
    steps:
      - name: deploy in UAT
        run: echo 'Im in UAT'

  prod:
    runs-on: ubuntu-latest
    needs:
      - dev-deploy
      - uat
    steps:
      - name: deploy in PROD
        run: echo 'Im in PROD'


