name: Expression
run-name: Expression | Debug

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: true

jobs:
  expression:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print start up date'
        #if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          echo "Github ==: ${{ github }}"
          # echo "Trigger by: ${{ github.event_name }}"
          # echo "Branch: ${{ github.ref }}"
          # echo "Commit SHA: ${{ github.sha }}"
          # echo "Runner OS: ${{ runner.os }}"

      - name: '[debug] Print when triggered from pp_dev'
        if: ${{ github.event.inputs.debug == 'true' && github.ref == 'refs/heads/pp_dev' }}
        run: echo "I was triggered from pp_dev"
