
name: Expression
run-name: Expression | Debug- ${{inputs.bebug && 'ONN' || 'OFF'}} 

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: true


jobs:
    expression:
        runs-on: ubuntu-latest
        steps:
         - name: '[debug] Print start up date'
           if: ${{inputs.bebug}}
           run: |
                echo "Trigger by: $${{github.event_name}}"
                echo "Branch: ${{github.ref}}"
                echo "Commit SHA: ${{github.sha}}"
                echo "Runner OS: ${{runner.os}}"

         - name: '[debug] Print when trigger from pp_dev'
           if: ${{inputs.bebug && github.ref == 'ref/headers/pp_dev'}}
           run: echo "I was trigger from pp_dev"
  
