name: Reusable workflow
description: Define reusable workflow

on:
  workflow_call:
    inputs:
      target-directory:
        type: string
        required: true

    outputs:
      build_status:
        description: "Build status from deploy job"
        value: ${{ jobs.deploy.outputs.build_status }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.build.outputs.build_status }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build
        id: build
        run: |
          echo "Building using directory: ${{ inputs.target-directory }}"
          echo "build_status=success" >> $GITHUB_OUTPUT

      - name: Deploy
        run: |
          echo 'Deploying build artifact...'
